# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoSuite_Latam
                                 A QGIS plugin
 Herramienta de estandarizacion y analisis de informacion cartografica
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-27
        copyright            : (C) 2024 by Automatizaciones Data Gis
        email                : juan.vargas@servinformacion.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
import sys

# PASO 1
# 1. Obtener la ruta de la subcarpeta que causa el conflicto
RUTA_ACTUAL = os.path.dirname(os.path.abspath(__file__))
RUTA_CONFLICTIVA = os.path.join(RUTA_ACTUAL, "Validaciones_CartoLATAM")

# 2. Inyectamos la subcarpeta en los módulos del sistema de Python.
# Al hacer esto, cuando QGIS intente hacer el `__import__` con la barra,
# Python creerá que ya fue cargado previamente y no arrojará el ModuleNotFoundError.
sys.path.append(RUTA_ACTUAL)

# Registramos el nombre problemático simulando que ya existe en el sistema
sys.modules['GeoSuite_Latam/Validaciones_CartoLATAM'] = sys.modules.get('GeoSuite_Latam')

# PASO 2
RUTA_COMPLEMENTO_B = os.path.join(RUTA_ACTUAL, "Validaciones_CartoLATAM")

# Si la carpeta del segundo plugin existe, le plantamos el archivo para que QGIS lo ignore
if os.path.exists(RUTA_COMPLEMENTO_B):
    archivo_skip = os.path.join(RUTA_COMPLEMENTO_B, ".qgis-skip")
    if not os.path.exists(archivo_skip):
        with open(archivo_skip, "w") as f:
            f.write("") # Crea el archivo vacío

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Validaciones_LATAM class from file Validaciones_LATAM.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Validaciones_LATAM import Validaciones_LATAM
    return Validaciones_LATAM(iface)
