name: Generar ZIP del Complemento

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permiso obligatorio para crear el Release
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Crear carpeta limpia y comprimir
        run: |
          mkdir GeoSuite_Latam
          rsync -av --exclude='.git*' --exclude='.github' ./ GeoSuite_Latam/
          zip -r GeoSuite_Latam.zip GeoSuite_Latam/

      - name: Publicar ZIP en Release Automático
        uses: "marvinpinto/action-automatic-releases@latest"  # Reemplazo oficial y actualizado
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Última Versión Estable (Automatizada)"
          files: |
            GeoSuite_Latam.zip